# Generated by Django 4.1.3 on 2022-11-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_lot', models.CharField(max_length=10)),
                ('qte_declare', models.IntegerField(max_length=10)),
                ('qte_saisie', models.IntegerField(max_length=10)),
                ('active', models.IntegerField(max_length=2)),
                ('annee', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
