# Generated by Django 4.1.3 on 2022-11-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('lots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lots',
            name='user',
            field=models.ManyToManyField(to='user.user'),
        ),
    ]
