# Generated by Django 4.1.3 on 2022-11-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0003_lots_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lots',
            name='active',
            field=models.IntegerField(max_length=10),
        ),
    ]
