# Generated by Django 4.1.3 on 2022-11-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='saisie',
            fields=[
                ('id_saisie', models.AutoField(primary_key=True, serialize=False)),
                ('Participation_id', models.CharField(max_length=100)),
                ('ancien_idPlateforme', models.CharField(max_length=100)),
                ('num_conso', models.CharField(max_length=100)),
                ('op_name', models.CharField(max_length=100)),
                ('civilite', models.CharField(max_length=10)),
                ('raison_social', models.CharField(max_length=100)),
                ('Nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('adresse1', models.CharField(max_length=100)),
                ('adresse2', models.CharField(max_length=100)),
                ('adresse3', models.CharField(max_length=100)),
                ('adresse4', models.CharField(max_length=100)),
                ('CodePostal', models.CharField(max_length=10)),
                ('ville', models.CharField(max_length=100)),
                ('pays', models.CharField(max_length=100)),
                ('langue', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Tel', models.CharField(max_length=100)),
                ('nombre_pneus_base', models.CharField(max_length=10)),
                ('diametre_pneus_base', models.CharField(max_length=10)),
                ('num_pdv_base', models.CharField(max_length=100)),
                ('date_achat_base', models.CharField(max_length=100)),
                ('optin_base', models.CharField(max_length=10)),
                ('optin_pdv_base', models.CharField(max_length=10)),
                ('optin_auto_base', models.CharField(max_length=10)),
                ('date_participation_base', models.CharField(max_length=100)),
                ('type_pneus_base', models.CharField(max_length=100)),
                ('idDotation_base', models.CharField(max_length=100)),
                ('Montant_base', models.CharField(max_length=100)),
                ('TypeBenefice_base', models.CharField(max_length=100)),
                ('TAS', models.CharField(max_length=100)),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('Date_Select', models.CharField(max_length=100)),
                ('Etat_select', models.CharField(max_length=100)),
                ('Date_Cloture', models.DateTimeField(auto_now=True)),
                ('Commentaire', models.CharField(max_length=100)),
                ('etat', models.CharField(max_length=100)),
            ],
        ),
    ]
