# Generated by Django 4.1.3 on 2022-11-23 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
        ('user', '0001_initial'),
        ('saisie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saisie',
            name='operation',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='operation.operation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saisie',
            name='user',
            field=models.OneToOneField(default=222, on_delete=django.db.models.deletion.DO_NOTHING, to='user.user'),
            preserve_default=False,
        ),
    ]
